ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDPISYiuYlCAMJovXfGTVfLojRGYle8QBJeS9tIjo1FMclQ1Yf7sX9VCYl7vctfh72ZyOtRkrnwFo6HCavR0jKABp+EXiOtLkHIMDb0ivn8eKMpF46+tqejROSKtzRUoudjFr1AAIGvP5mbIkk/TSN0MgqrDQlJ6CKbko+WPO9lcCs8mrqW8vWOOCCbkk8H4oNNLBeqoWXWZVZgPBcuhkxhUqEjx7w9VyV5jXia5oEGZpsfFbt6B5Rw1UitKEFt3S9zUkyOecA6uSFkKD0fuobJsJulCn8HKr0IvFpDGxsSrlIT1iQVgOGNUPe7c68c2Tlzh4piMOEXYFToR2Tey0lNimSrjHzc78XfK//aq5lKtYSKtI//mY57gk+1aBThVIDwVflgVKHjxU2zm1M53yiswFZVMP3Ou4vWnqYom3BiQJijexfSjIrX0AXiuRSTNd/HN77cb8kNmFnj/aid8qSQLS1Q8rE14BCEm0quUGBNfwDeGF4X4B6MlkBwv3Oo+HDx/UMy2CA5c48s/2Spgd8odCnPkXDWxnzsM2mdX21SowINrKkg/h2W5UFUtAm83/ah1eVEwRjxsTPaZGUz1HOBERwNQtxwZxO5ml7Ir0jBXSobaPUKybFw08zIY3BVOxVaFoy0DLmjbO7Sq9+rWXr6aCVnFEPv4szJ6AZRaZ/OAQ== lajoiec@dominos
hostname: k3os
k3os:
  password: rancher
  token: k3os
  k3s_args:
    - server
    - "--cluster-cidr=172.16.0.0/12"
    - "--cluster-domain=dpz.local"
    - "--disable-cloud-controller"
    - "--service-cidr=10.249.249.0/24"
